function [folder,subFolders] = pathmd ()

folder = '/Users/tobyhawes/Documents/Dissertation/labfem2d-3/';

subFolders = {'boundaryconditions/',...
              'errors/',...
              'matrices/',...
              'meshes/',...
              'numericalintegration/',...
              'problems/',...
              'solvers/',...
              'timeschemes/',...
              'visualization/'};

end